<?php
$error = '';
$success = '';

// Security: Prevent re-running the installer
if (file_exists('install.lock')) {
    die("<div style='font-family: sans-serif; padding: 2rem; text-align: center;'>
            <h2>Installation Locked</h2>
            <p>The system is already installed. To run this wizard again, delete the <b>install.lock</b> file.</p>
         </div>");
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $driver = $_POST['driver'] ?? 'mysql';
    $host   = $_POST['host'] ?? 'localhost';
    $db     = $_POST['db'] ?? '';
    $user   = $_POST['user'] ?? '';
    $pass   = $_POST['pass'] ?? '';

    try {
        // 1. Attempt Database Connection
        $dsn = $driver === 'mysql' 
            ? "mysql:host=$host;dbname=$db;charset=utf8mb4" 
            : "pgsql:host=$host;dbname=$db";
        
        $pdo = new PDO($dsn, $user, $pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
        ]);

        // 2. Determine Primary Key Syntax based on DB Driver
        $pk_syntax = $driver === 'mysql' ? 'INT AUTO_INCREMENT PRIMARY KEY' : 'SERIAL PRIMARY KEY';

        // 3. Define Table Schema Queries
        $queries = [
            "CREATE TABLE IF NOT EXISTS clients (
                id $pk_syntax,
                name VARCHAR(255) NOT NULL,
                email VARCHAR(255) NOT NULL,
                company VARCHAR(255),
                address TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )",
            "CREATE TABLE IF NOT EXISTS products (
                id $pk_syntax,
                name VARCHAR(255) NOT NULL,
                description TEXT,
                price DECIMAL(10, 2) NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )",
            "CREATE TABLE IF NOT EXISTS invoices (
                id $pk_syntax,
                client_id INT NOT NULL,
                invoice_number VARCHAR(50) NOT NULL UNIQUE,
                status VARCHAR(20) DEFAULT 'draft',
                type VARCHAR(20) DEFAULT 'invoice',
                issue_date DATE NOT NULL,
                due_date DATE,
                total_amount DECIMAL(10, 2) DEFAULT 0.00,
                stripe_payment_intent_id VARCHAR(255),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )",
            "CREATE TABLE IF NOT EXISTS invoice_items (
                id $pk_syntax,
                invoice_id INT NOT NULL,
                product_id INT,
                description TEXT NOT NULL,
                quantity INT NOT NULL DEFAULT 1,
                unit_price DECIMAL(10, 2) NOT NULL,
                subtotal DECIMAL(10, 2) NOT NULL
            )"
        ];

        // 4. Execute Table Creation
        foreach ($queries as $sql) {
            $pdo->exec($sql);
        }

        // 5. Generate and Write db.php
        $config_content = "<?php\n" .
            "// Auto-generated by install.php\n" .
            "\$db_driver = '$driver';\n" .
            "\$db_host   = '$host';\n" .
            "\$db_name   = '$db';\n" .
            "\$db_user   = '$user';\n" .
            "\$db_pass   = '$pass';\n\n" .
            "try {\n" .
            "    \$dsn = \$db_driver === 'mysql' \n" .
            "        ? \"mysql:host=\$db_host;dbname=\$db_name;charset=utf8mb4\" \n" .
            "        : \"pgsql:host=\$db_host;dbname=\$db_name\";\n" .
            "    \$pdo = new PDO(\$dsn, \$db_user, \$db_pass, [\n" .
            "        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,\n" .
            "        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC\n" .
            "    ]);\n" .
            "} catch (PDOException \$e) {\n" .
            "    die('Database connection failed: ' . \$e->getMessage());\n" .
            "}\n";

        if (file_put_contents('db.php', $config_content) === false) {
            throw new Exception("Could not write to db.php. Check your directory permissions.");
        }

        // 6. Create lock file
        file_put_contents('install.lock', 'Locked. Delete this file to reinstall.');

        $success = "Database configured and tables created! You are ready to go.";

    } catch (PDOException $e) {
        $error = "Database Error: " . $e->getMessage();
    } catch (Exception $e) {
        $error = "System Error: " . $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SwiftBill - System Setup</title>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
</head>
<body class="bg-slate-100 flex items-center justify-center min-h-screen p-4 font-sans text-slate-800">

    <div class="max-w-md w-full bg-white rounded-xl shadow-lg border border-slate-200 overflow-hidden">
        <div class="bg-slate-900 p-6 text-center">
            <h1 class="text-2xl font-bold text-white tracking-tight">⚡ SwiftBill Setup</h1>
            <p class="text-slate-400 text-sm mt-1">Connect your database to generate tables</p>
        </div>

        <div class="p-6">
            <?php if ($error): ?>
                <div class="bg-red-50 text-red-700 border border-red-200 p-3 rounded-lg text-sm mb-5 font-medium">
                    <?= htmlspecialchars($error) ?>
                </div>
            <?php endif; ?>

            <?php if ($success): ?>
                <div class="bg-emerald-50 text-emerald-700 border border-emerald-200 p-4 rounded-lg text-center mb-5">
                    <p class="font-bold text-lg mb-1">Success!</p>
                    <p class="text-sm mb-4"><?= htmlspecialchars($success) ?></p>
                    <a href="index.php" class="inline-block bg-slate-900 hover:bg-slate-800 text-white font-medium py-2 px-6 rounded transition">
                        Go to Dashboard
                    </a>
                </div>
            <?php else: ?>
                <form method="POST" action="" class="space-y-4">
                    
                    <div>
                        <label class="block text-sm font-semibold mb-1 text-slate-700">Database Driver</label>
                        <select name="driver" class="w-full border border-slate-300 rounded-lg p-2.5 bg-slate-50 focus:ring-2 focus:ring-indigo-500 focus:outline-none">
                            <option value="mysql">MySQL / MariaDB</option>
                            <option value="pgsql">PostgreSQL</option>
                        </select>
                    </div>

                    <div>
                        <label class="block text-sm font-semibold mb-1 text-slate-700">Host (usually localhost)</label>
                        <input type="text" name="host" value="localhost" required class="w-full border border-slate-300 rounded-lg p-2.5 bg-slate-50 focus:ring-2 focus:ring-indigo-500 focus:outline-none">
                    </div>

                    <div>
                        <label class="block text-sm font-semibold mb-1 text-slate-700">Database Name</label>
                        <input type="text" name="db" placeholder="e.g., swiftbill" required class="w-full border border-slate-300 rounded-lg p-2.5 bg-slate-50 focus:ring-2 focus:ring-indigo-500 focus:outline-none">
                    </div>

                    <div class="grid grid-cols-2 gap-4">
                        <div>
                            <label class="block text-sm font-semibold mb-1 text-slate-700">Username</label>
                            <input type="text" name="user" required class="w-full border border-slate-300 rounded-lg p-2.5 bg-slate-50 focus:ring-2 focus:ring-indigo-500 focus:outline-none">
                        </div>
                        <div>
                            <label class="block text-sm font-semibold mb-1 text-slate-700">Password</label>
                            <input type="password" name="pass" class="w-full border border-slate-300 rounded-lg p-2.5 bg-slate-50 focus:ring-2 focus:ring-indigo-500 focus:outline-none">
                        </div>
                    </div>

                    <button type="submit" class="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 px-4 rounded-lg mt-4 shadow-sm transition">
                        Install & Create Tables
                    </button>
                </form>
            <?php endif; ?>
        </div>
    </div>

</body>
</html>